In [191]:
import sys, os
import numpy as np
from scipy.linalg import lu

### Verifying the LU decomposition for Q1 

In [204]:
# I did not find built in function that does the LU without pivoting so I just used prof.Matteo's code from the LU notebook with some alterations
def LU(A):
    U = np.copy(A)
    m, n = A.shape  # m = number of rows, n = number of columns
    L = np.eye(m)  # L should be a square matrix of size m x m
    for k in range(min(m, n)-1): 
        if np.all(U[k+1:, k] == 0): #skip columns with zero entries below the pivot 
            continue
        for j in range(k+1, m):  
            L[j, k] = U[j, k] / U[k, k]
            U[j, k:n] -= L[j, k] * U[k, k:n]
    return L, U



In [205]:
A_a = np.array([[2,6,-2,0,2],[3,9,-3,3,1],[-1,-3,1,-3,1]]).astype(float)

print(A_a)

[[ 2.  6. -2.  0.  2.]
 [ 3.  9. -3.  3.  1.]
 [-1. -3.  1. -3.  1.]]


In [206]:
L_a, U_a = LU(A_a)

print('L=',L_a)
print('U=', U_a)

L= [[ 1.   0.   0. ]
 [ 1.5  1.   0. ]
 [-0.5  0.   1. ]]
U= [[ 2.  6. -2.  0.  2.]
 [ 0.  0.  0.  3. -2.]
 [ 0.  0.  0. -3.  2.]]


In [207]:
A_b = np.array([[2,4,2],[1,-1,3],[-1,7,-7]]).astype(float)

print(A_b)

[[ 2.  4.  2.]
 [ 1. -1.  3.]
 [-1.  7. -7.]]


In [208]:
L_b, U_b = LU(A_b)

print('L=',L_b)
print('U=', U_b)

L= [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -3.   1. ]]
U= [[ 2.  4.  2.]
 [ 0. -3.  2.]
 [ 0.  0.  0.]]


In [209]:
A_c = np.array([[2,2,-2,4,2],[1,-1,0,2,1],[3,1,-2,6,3],[1,3,-2,2,1]]).astype(float)

print(A_c)

[[ 2.  2. -2.  4.  2.]
 [ 1. -1.  0.  2.  1.]
 [ 3.  1. -2.  6.  3.]
 [ 1.  3. -2.  2.  1.]]


In [210]:
L_c, U_c = LU(A_c)

print('L=',L_c)
print('U=', U_c)

L= [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 1.5  1.   1.   0. ]
 [ 0.5 -1.   0.   1. ]]
U= [[ 2.  2. -2.  4.  2.]
 [ 0. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


### Verifying the LU decomposition for Q2 

In [28]:
import numpy as np
from scipy.linalg import lu

In [98]:
A_2 = np.array([[0,0,2],[0,-1,4],[3,5,1]]).astype(float)


P1, L1, U1 = lu(A_2)

print('A=', A_2)
print('P=', P1)
print('L=', L1)
print('U=', U1)

A= [[ 0.  0.  2.]
 [ 0. -1.  4.]
 [ 3.  5.  1.]]
P= [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
U= [[ 3.  5.  1.]
 [ 0. -1.  4.]
 [ 0.  0.  2.]]


In [35]:
B_2 = np.array([[0,-1,2,1,3],[-1,1,3,1,4],[1,-1,-3,6,2],[2,-2,-4,1,0]]).astype(float)


P2, L2, U2 = lu(B_2)

print('A=', B_2)
print('P=', P2)
print('L=', L2)
print('U=', U2)

A= [[ 0. -1.  2.  1.  3.]
 [-1.  1.  3.  1.  4.]
 [ 1. -1. -3.  6.  2.]
 [ 2. -2. -4.  1.  0.]]
P= [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L= [[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.5 -0.   1.   0. ]
 [-0.5 -0.  -1.   1. ]]
U= [[ 2.  -2.  -4.   1.   0. ]
 [ 0.  -1.   2.   1.   3. ]
 [ 0.   0.  -1.   5.5  2. ]
 [ 0.   0.   0.   7.   6. ]]


In [36]:
C_2 = np.array([[-1,-2,3,0],[2,4,-6,5],[1,1,-1,3],[2,5,-10,1]]).astype(float)


P3, L3, U3 = lu(C_2)

print('A=', C_2)
print('P=', P3)
print('L=', L3)
print('U=', U3)

A= [[ -1.  -2.   3.   0.]
 [  2.   4.  -6.   5.]
 [  1.   1.  -1.   3.]
 [  2.   5. -10.   1.]]
P= [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
L= [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 1.  -1.   1.   0. ]
 [-0.5 -0.  -0.   1. ]]
U= [[ 2.   4.  -6.   5. ]
 [ 0.  -1.   2.   0.5]
 [ 0.   0.  -2.  -3.5]
 [ 0.   0.   0.   2.5]]


#### probalby I am having a different PLU here than my PLU found by hand calculations because LU decomposition is not unique, you can have different possible choices.




## Q4

In [90]:
def lufactors(A):
    """
    Performs LU decomposition on a nxn or mxn matrix A.
    The code checks each column and skips elimination for columns where all entries below the pivot are already zero
    to avoid divison by zero if encountered any zero pivot.
    
    No pivoting
    
    Parameters:
    A matrix of either shapes nxn or mxn
    
    Returns:
    L: Lower triangular matrix
    U: Upper triangular matrix 
    
    """
    # dimensions of matrix A
    m, n = A.shape
    
    # Initialize L as identity matrix of shape (m x m) and U as a copy of A
    L = np.eye(m, dtype=float)
    U = np.copy(A).astype(float) 
    
    # Perform Gaussian elimination to transform U into an upper triangular matrix
    for k in range(min(m, n) - 1):  # Iterate through columns
        
        if np.all(U[k + 1:, k] == 0):  # If all entries below the current column U[k, k] are zero, skip this column and move to the next
            continue  

        for j in range(k + 1, m):  # Iterate over rows below the pivot
            if U[k, k] != 0:  # Check if the pivot is non-zer0
                multiplier = U[j, k] / U[k, k] # Calculate the multiplier for elimination
                L[j, k] = multiplier  # Store the multiplier in L
                U[j, k:n] -= multiplier * U[k, k:n]  # Elimination 

    return L, U




#### Testing the code on the matrices from Q1 since it is done by hand (for validation)

In [212]:
[L, U] = lufactors(A_a)

print('L=',L)
print('U=',U)

L= [[ 1.   0.   0. ]
 [ 1.5  1.   0. ]
 [-0.5  0.   1. ]]
U= [[ 2.  6. -2.  0.  2.]
 [ 0.  0.  0.  3. -2.]
 [ 0.  0.  0. -3.  2.]]


In [213]:
np.allclose(L, L_a)

True

In [214]:
[L, U] = lufactors(A_b)

print('L=',L)
print('U=',U)

L= [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -3.   1. ]]
U= [[ 2.  4.  2.]
 [ 0. -3.  2.]
 [ 0.  0.  0.]]


In [215]:
np.allclose(L, L_b)

True

In [216]:
[L, U] = lufactors(A_c)

print('L=',L)
print('U=',U)

L= [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 1.5  1.   1.   0. ]
 [ 0.5 -1.   0.   1. ]]
U= [[ 2.  2. -2.  4.  2.]
 [ 0. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [217]:
np.allclose(L, L_c)

True

### Q5

In [101]:
def forwardsubst(L, b):
    """
    Solves the lower triangular system L * y = b using forward substitution.
    
    Parameters:
    L: Lower triangular matrix of shape (m, m)
    b: Right-hand side column vector of shape (m,)
    
    Returns:
    y: Solution of the system (m,)
    
    """
    
    m = L.shape[0]
    
    # Initialize vector y with zeros
    y = np.zeros_like(b, dtype=float)
    
    # Perform forward substitution
    for i in range(m):
        sum_l_y = sum(L[i, j] * y[j] for j in range(i))  # Sum of L[i, j] * y[j] for j < i
        y[i] = (b[i] - sum_l_y) / L[i, i]
        
    return y

In [106]:
# Use the following system to verify question 5 and 6 also Q4 can be validated by this example too. 
#used the following example from https://www.youtube.com/watch?v=m3EojSAgIao (since it is solved, so that I know what I got is correct) 
A_ex = np.array([[1,1,-1],[1,-2,3],[2,3,1]])
b_ex = np.array([[4],[-6],[7]])

print('A_ex=', A_ex)
print('b_ex=', b_ex)

A_ex= [[ 1  1 -1]
 [ 1 -2  3]
 [ 2  3  1]]
b_ex= [[ 4]
 [-6]
 [ 7]]


In [129]:
#Use the LU code in Q4 to decompose A_ex
[L_ex, U_ex] = lufactors(A_ex)

print('L=',L_ex)
print('U=',U_ex)

print('A=LU=', L_ex@U_ex)

L= [[ 1.          0.          0.        ]
 [ 1.          1.          0.        ]
 [ 2.         -0.33333333  1.        ]]
U= [[ 1.          1.         -1.        ]
 [ 0.         -3.          4.        ]
 [ 0.          0.          4.33333333]]
A=LU= [[ 1.  1. -1.]
 [ 1. -2.  3.]
 [ 2.  3.  1.]]


In [111]:
#To find y 
y_ex= forwardsubst(L_ex,b_ex)

print('y=',y_ex)

y= [[  4.        ]
 [-10.        ]
 [ -4.33333333]]


### Q6


In [152]:
def backsubst(U, y):
    """
    Solves the upper triangular system U * x = y using back substitution.
    Supports non-square upper triangular matrices with more rows than columns (m >= n).
    
    Parameters:
    U: Upper triangular matrix of shape (m, n) where m >= n
    y: Right-hand side column vector of shape (m,)
    
    Returns:
    x: Solution of the system (n,)
    """
    
    m, n = U.shape

    # Initialize the solution vector x with zeros of shape (n,)
    x = np.zeros(n, dtype=float)

    # Perform back substitution 
    for i in range(min(m, n)-1, -1, -1):  # Iterate from min(m, n)-1 to 0 (inclusive)
        sum_u_x = sum(U[i, j] * x[j] for j in range(i + 1, n))  # Sum of U[i, j] * x[j] for j > i
        x[i] = (y[i] - sum_u_x) / U[i, i]
        x = x.reshape(-1, 1)

    return x


In [117]:
# To find x for the same example earlier 
x_ex=backsubst(U_ex, y_ex)

print('x=',x_ex)

x= [[ 1.]
 [ 2.]
 [-1.]]


### Q7

$$
\begin{bmatrix}
1 & 1 & 1 \\
1 & 2 & 4 \\
1 & 3 & 9 \\
\end{bmatrix}
\begin{bmatrix}
c_1 \\
c_2 \\
c_3
\end{bmatrix}
=
\begin{bmatrix}
11 \\
12.5 \\
14 \\
\end{bmatrix}
$$

In [131]:
A_7 = np.array([[1,1,1],[1,2,4],[1,3,9]]).astype(float)
print('A=',A_7)

b_7 = np.array([[11],[12.5],[14]]).astype(float)
print('b=', b_7)

A= [[1. 1. 1.]
 [1. 2. 4.]
 [1. 3. 9.]]
b= [[11. ]
 [12.5]
 [14. ]]


In [132]:
# First, decompose A using the LU decomposition code from Q4
[L_7, U_7] = lufactors(A_7)

print('L=',L_7)
print('U=',U_7)

L= [[1. 0. 0.]
 [1. 1. 0.]
 [1. 2. 1.]]
U= [[1. 1. 1.]
 [0. 1. 3.]
 [0. 0. 2.]]


In [133]:
# Second, solve the system L y = b by forward substitution using the code from Q5
y_7= forwardsubst(L_7,b_7)

print('y=',y_7)

y= [[11. ]
 [ 1.5]
 [ 0. ]]


In [135]:
# Finally, solve the system U x = y by backward substitution using the code from Q6
x_7=backsubst(U_7, y_7)

print('x=',x_7)

x= [[9.5]
 [1.5]
 [0. ]]


### 
Hence, 

$$
x=
\begin{bmatrix}
c_1 \\
c_2 \\
c_3
\end{bmatrix}
=
\begin{bmatrix}
9.5 \\
1.5 \\
0\\
\end{bmatrix}
$$

These are the values for the coefficients c1, c2 and c3 that makes p(t)=f(t) for the given t values. Thus, the quadratic polynomial that fits the given points is p(t)=9.5+1.5t

### Q8

This is the linear system to solve in order to determine the messages were all the code vectors b were stacked in one matrix $B = \begin{bmatrix} \mathbf{b}_1 & \mathbf{b}_2 & \cdots & \mathbf{b}_9 \end{bmatrix}$ and all the corresponding vectors x (that will contain the encoded message) were stacked in the matrix $X = \begin{bmatrix} \mathbf{x}_1 & \mathbf{x}_2 & \cdots & \mathbf{x}_9 \end{bmatrix}$

$$
AX = B
$$

$$
\begin{bmatrix}
2 & 3 & 8 \\
0 & 1 & 4 \\
1 & 0 & -3 \\
\end{bmatrix}
\begin{bmatrix}
\mathbf{x}_1 & \mathbf{x}_2 & \cdots & \mathbf{x}_9
\end{bmatrix}
=
\begin{bmatrix}
162 & 51 & 125 & 85 & 66 & 233 & 241 & 187 & 257\\
48 & 9 & 31 & 27 & 22 & 85 & 93 & 79 & 113\\
0 & 11 & 15 & -3 & -1 & -30 & -42 & -40 & -68\\
\end{bmatrix}
$$













In [143]:
A_8 = np.array([[2,3,8],[0,1,4],[1,0,-3]]).astype(float)
print('A=',A_8)

B_8 = np.array([[162,51,125,85,66,233,241,187,257],[48,9,31,27,22,85,93,79,113],[0,11,15,-3,-1,-30,-42,-40,-68]]).astype(float)
print('B=', b_8)

A= [[ 2.  3.  8.]
 [ 0.  1.  4.]
 [ 1.  0. -3.]]
B= [[162.  51. 125.  85.  66. 233. 241. 187. 257.]
 [ 48.   9.  31.  27.  22.  85.  93.  79. 113.]
 [  0.  11.  15.  -3.  -1. -30. -42. -40. -68.]]


In [144]:
# Decompose A=LU
[L_8, U_8] = lufactors(A_8)

print('L=',L_8)
print('U=',U_8)

L= [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.5 -1.5  1. ]]
U= [[ 2.  3.  8.]
 [ 0.  1.  4.]
 [ 0.  0. -1.]]


In [145]:
# Solve L Y = B
Y_8= forwardsubst(L_8,B_8)

print('Y=',Y_8)

Y= [[162.  51. 125.  85.  66. 233. 241. 187. 257.]
 [ 48.   9.  31.  27.  22.  85.  93.  79. 113.]
 [ -9.  -1.  -1.  -5.  -1. -19. -23. -15. -27.]]


In [153]:
# Solve U X = Y
X_8=backsubst(U_8, Y_8.flatten())

print('X=',X_8)

X= [[-245.5]
 [ 551. ]
 [-125. ]]


In [189]:
X_vecs = []

# Loop through each column of Y and solve the system
for j in range(Y_8.shape[1]):  # Iterate over the number of columns in Y
    y_column = Y_8[:, j]  # Extract the j-th column of Y
    X_vecs.append(backsubst(U_8, y_column))

# # Print all solutions
# for i, X in enumerate(X_vecs):
#     print(f'Solution for column {i + 1} of Y: \n{X}\n')
    
X_8=np.hstack(X_vecs) 
print('This is the encoded message matrix X, were each column is a vecotr x_i that correspond to vector b_i')
print('X=',X_8)# Matrix X where each column is a vecotr x_i that correspond to vector b_i

This is the encoded message matrix X, were each column is a vecotr x_i that correspond to vector b_i
X= [[27. 14. 18. 12.  2. 27. 27.  5. 13.]
 [12.  5. 27.  7. 18.  9.  1. 19.  5.]
 [ 9.  1.  1.  5.  1. 19. 23. 15. 27.]]


In [184]:
# Build a function for decoding that iterates through columns of the matrix X 
def decode_messages(X):
    # Define the letter mapping: 1-26 for 'A'-'Z' and 27 for space
    alphabet = {i: chr(64 + i) for i in range(1, 27)}  # a dictionary for A-Z
    alphabet[27] = ' '  # 27-space
    
    # Iterate through each column of matrix X (which represents each message vector)
    message = '' # An empty string to store the decoded message
    for col in range(X.shape[1]):
        # Convert each column to a row and map each number to its corresponding letter
        message_vector = ''.join([alphabet.get(int(round(X[row, col])), '?') for row in range(X.shape[0])])
        message += message_vector + ' '  # Add a space between each decoded message part

    return message


In [190]:
X8_message = decode_messages(X_8)

print('The message is:',X8_message)# view the message 'LINEAR ALGEBRA IS AWESOME'

The message is:  LI NEA R A LGE BRA  IS  AW ESO ME  


### If we receive each vector individually

LU decomposition done using the code from Q4

For the rest of the steps one can combine all the functions in one function that does it all and keeps on using it for each vector individually 

In [169]:
# A big function to perform forward and backward substitutio and decode the message taking one vector b at a time

def get_message(L, U, b):
    
    # 1. solve L y = b using forward substitution
    y = forwardsubst(L,b)

    # 2. solve U x = y using back substitution
    x = backsubst(U, y)
    
    #3. decode the vector and map it to letters
    
    alphabet = {i: chr(64 + i) for i in range(1, 27)}  
    alphabet[27] = ' '  

    
    decoded_message = ''.join([alphabet.get(int(round(x[i, 0])), '?') for i in range(x.shape[0])])

   
    return decoded_message

In [174]:
# the code vectors
b_1 = np.array([[162],[48],[0]])
b_2 = np.array([[51],[9],[11]])
b_3 = np.array([[125],[31],[15]])
b_4 = np.array([[85],[27],[-3]])
b_5 = np.array([[66],[22],[-1]])
b_6 = np.array([[233],[85],[-30]])
b_7 = np.array([[241],[93],[-42]])
b_8 = np.array([[187],[79],[-40]])
b_9 = np.array([[257],[113],[-68]])


In [180]:
# the corresponding decoded vecotrs or the factors 
x_1=get_message(L_8,U_8,b_1)
x_2=get_message(L_8,U_8,b_2)
x_3=get_message(L_8,U_8,b_3)
x_4=get_message(L_8,U_8,b_4)
x_5=get_message(L_8,U_8,b_5)
x_6=get_message(L_8,U_8,b_6)
x_7=get_message(L_8,U_8,b_7)
x_8=get_message(L_8,U_8,b_8)
x_9=get_message(L_8,U_8,b_9)

In [181]:
print(x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9) # see the message 

 LI NEA R A LGE BRA  IS  AW ESO ME 


### Assume that both the original message and the encoded one are available, but not the 3x3 matrix A. Can one determine A? If so, describe how this can be done.

ans: yes A can be determined. If the decoded message matrix X is square and invertible(non-singular) one can invert for A:

$$
AX = B
$$

$$
A = B X^{-1} 
$$

If X is not square then one can use pseudoinverse to invert for A:
$$
A = BX^{+} 
$$

### Assume that A is singular. Can one determine the message ?

ans: If the matrix is singular(not invertble) the system $AX = B$ will either have no solution whcih means one can't determine the message, or the system will have infinite number of solutions(no unique solution) which can be found by pseudoinverse, but doesn't guarantee that we can determine the message uniqely(the original message) without additional information.