In [1]:
import numpy as np 


In [5]:
A = np.array ([[9, 7, 10, 8], [-13, 1, 5, -6]])

print(A)

[[  9   7  10   8]
 [-13   1   5  -6]]


In [7]:
AT= A.T

In [9]:
ATA = np.dot(AT, A)

print(ATA)

[[250  50  25 150]
 [ 50  50  75  50]
 [ 25  75 125  50]
 [150  50  50 100]]


In [29]:
AAT = np.dot(A, AT)

print(AAT)

[[ 294 -108]
 [-108  231]]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(ATA)


print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [ 3.75000000e+02  1.50000000e+02  5.05193544e-14 -4.55922620e-15]
Eigenvectors:
 [[-7.74596669e-01  4.08248290e-01 -4.48768918e-01 -4.49276327e-02]
 [-2.58198890e-01 -4.08248290e-01  3.87054419e-01 -8.62669660e-01]
 [-2.58198890e-01 -8.16496581e-01 -4.17911669e-01  4.08871014e-01]
 [-5.16397779e-01  3.52274196e-16  6.88582001e-01  2.94290772e-01]]


In [30]:
X = np.array ([[-3, 11], [10, -2], [1, 5], [-4, 6]])

print(X)

[[-3 11]
 [10 -2]
 [ 1  5]
 [-4  6]]


In [31]:
XT= X.T

In [32]:
XXT = np.dot(X, XT)

print(XXT)

[[130 -52  52  78]
 [-52 104   0 -52]
 [ 52   0  26  26]
 [ 78 -52  26  52]]


In [33]:
eigenvalues, eigenvectors = np.linalg.eig(XXT)


print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [ 2.34000000e+02 -5.25271166e-15  7.80000000e+01  5.99968687e-15]
Eigenvectors:
 [[-7.07106781e-01  5.77350269e-01 -4.08248290e-01  2.91229012e-01]
 [ 4.71404521e-01 -1.44567339e-16 -8.16496581e-01  2.87818806e-01]
 [-2.35702260e-01 -5.77350269e-01 -4.08248290e-01 -8.66866625e-01]
 [-4.71404521e-01 -5.77350269e-01 -7.75002417e-17  2.84408600e-01]]


In [37]:
e = np.array([[3, 7, 1, 5], [3, 1, 7, 5], [6, 2, 2, -2]])

print(e)

[[ 3  7  1  5]
 [ 3  1  7  5]
 [ 6  2  2 -2]]


In [35]:
eT = e.T

In [39]:
eTe = np.dot(eT, e)

print(eTe)

[[54 36 36 18]
 [36 54 18 36]
 [36 18 54 36]
 [18 36 36 54]]


In [40]:
eigenvalues, eigenvectors = np.linalg.eig(eTe)


print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [1.44000000e+02 2.10398438e-14 3.60000000e+01 3.60000000e+01]
Eigenvectors:
 [[ 5.00000000e-01  5.00000000e-01  7.07106781e-01 -2.79624878e-01]
 [ 5.00000000e-01 -5.00000000e-01 -4.95279600e-16 -6.49468958e-01]
 [ 5.00000000e-01 -5.00000000e-01  3.59056936e-16  6.49468958e-01]
 [ 5.00000000e-01  5.00000000e-01 -7.07106781e-01  2.79624878e-01]]


In [16]:
def gaussian_elimination(A):
    n = len(A)
    
    for i in range(n):
        # Find the pivot
        max_row = i + np.argmax(abs(A[i:, i]))
        # Swap the current row with the pivot row
        A[[i, max_row]] = A[[max_row, i]]
        
        # Make the diagonal element 1 and eliminate the column below it
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
    
    return A



In [20]:
ATA_375 = np.array ([[-125, 50, 25, 150, 0], [50, -325, 75, 50, 0], [25, 75, -250, 50, 0], [150, 50, 50, -275,0]], dtype=float)

print(ATA_375)

[[-125.   50.   25.  150.    0.]
 [  50. -325.   75.   50.    0.]
 [  25.   75. -250.   50.    0.]
 [ 150.   50.   50. -275.    0.]]


In [24]:
k = gaussian_elimination(ATA_375.copy())

print("Row Echelon Form:")
print(k)

Row Echelon Form:
[[ 1.50000000e+02  5.00000000e+01  5.00000000e+01 -2.75000000e+02
   0.00000000e+00]
 [ 0.00000000e+00 -3.41666667e+02  5.83333333e+01  1.41666667e+02
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.46951220e+02  1.23475610e+02
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.42108547e-14
   0.00000000e+00]]


In [25]:
def back_substitution(U):
    n = len(U)
    x = np.zeros(n)
    
    for i in range(n - 1, -1, -1):
        x[i] = (U[i, -1] - np.sum(U[i, i + 1:n] * x[i + 1:n])) / U[i, i]
    
    return x

In [28]:
solution = back_substitution(k)

print("Solution:")
print(solution)

Solution:
[ 0. -0. -0. -0.]
