![Q6](HW1_Q6.jpg)

In [1]:
import numpy as np 

In [2]:
A = np.array([[1, 2], [3, 4], [1, 1],[1, -1]])

print('A=',A)

b= np.array([[1],[2], [3], [4]])

print('b=',b)

A= [[ 1  2]
 [ 3  4]
 [ 1  1]
 [ 1 -1]]
b= [[1]
 [2]
 [3]
 [4]]


In [6]:
U, S, VT = np.linalg.svd(A, full_matrices=True) #get only u and v vectors that corresponds to non-zero singular values

print('U=',U)
print('Vt=',VT)
print('S=',S)

U= [[-0.39165244  0.22910853 -0.11260607  0.88398955]
 [-0.8853506  -0.10135071 -0.22410732 -0.3945355 ]
 [-0.24684908 -0.16522962  0.95328474  0.05488993]
 [ 0.04275765 -0.95390591 -0.1683567   0.24472702]]
Vt= [[-0.57604844 -0.81741556]
 [-0.81741556  0.57604844]]
S= [5.64500387 1.46079816]


In [8]:
U_col = U[:, :2]
U_null = U[:, 2:]


print('U_C(A)=',U_col)
print('U_N(A^T)=',U_null)

U_C(A)= [[-0.39165244  0.22910853]
 [-0.8853506  -0.10135071]
 [-0.24684908 -0.16522962]
 [ 0.04275765 -0.95390591]]
U_N(A^T)= [[-0.11260607  0.88398955]
 [-0.22410732 -0.3945355 ]
 [ 0.95328474  0.05488993]
 [-0.1683567   0.24472702]]


In [14]:
# projecting b onto the column space of A using U with only left singular vectors that corresponds to non-zero singular values (they are the basis for the column space of A)    
b_hat = U_col @ U_col.T @ b

print('b_hat =',b_hat)

b_hat = [[0.08823529]
 [2.85294118]
 [1.38235294]
 [3.97058824]]


In [15]:
z=b-b_hat

print('z=',z)

z= [[ 0.91176471]
 [-0.85294118]
 [ 1.61764706]
 [ 0.02941176]]


### The checking 

For $\hat{b}$ to be in the column space of A, it is supposed to be able to be expressed as a linear combination of the columns of U that correspond to the non-zero singular values (since they are the basis for the C(A)). Also, it should be orthogonal to all vectors in the left null space since C(A) and N($A^T$) are orthogonal complements, hence, vectors lie within them need to verify that.

In [10]:
# check orthogonality 

b_hat_ortho = U_null.T @ b_hat


print(b_hat_ortho) 

#on the order of 10^-16 and 10^-15 are practically zero, hence, b_hat is orthogonal to the N(A^T) basis.

[[-3.15837089e-16]
 [-1.41320692e-15]]


In [20]:
# check linear combination

x = np.linalg.lstsq(U_col, b_hat, rcond=None)[0]


linear_comb_b_hat = U_col @ x


print('x=',x)
print('b_hat from the linear combination=',linear_comb_b_hat)

#which indeed shows that b_hat can be expressed as a linear combination of the basis of C(A).

x= [[-2.73187025]
 [-4.28490541]]
b_hat from the linear combination= [[0.08823529]
 [2.85294118]
 [1.38235294]
 [3.97058824]]
