In [1]:
import numpy as np 

In [2]:
A = np.array([[1, 2], [3, 4], [1, 1],[1, -1]])

print(A)

b= np.array([[1],[2], [3], [4]])

print(b)

[[ 1  2]
 [ 3  4]
 [ 1  1]
 [ 1 -1]]
[[1]
 [2]
 [3]
 [4]]


In [3]:
U, Sigma, VT = np.linalg.svd(A)

In [11]:
S = np.zeros((U.shape[0], VT.shape[0]))
np.fill_diagonal(S, Sigma)

In [12]:
b_hat = U @U.T @ b

print(b_hat)

[[1.]
 [2.]
 [3.]
 [4.]]


In [13]:
z=b-b_hat

print(z)

[[ 6.66133815e-16]
 [-4.44089210e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [14]:
check_col_space = np.allclose(b_hat, U @U.T @ b)

print(check_col_space)

True


In [24]:
from scipy.linalg import svd

U, S, Vt = svd(A, full_matrices=False)

#print(U)
#print(Vt)
#print(S)

[5.64500387 1.46079816]


In [25]:

# Step 2: Calculate the pseudoinverse of the diagonal matrix Sigma
S_inv = np.diag(1/S)

# Step 3: Compute the projection of b onto the column space of A (b_hat)
# Projection is U_r U_r^T b where U_r are the first r columns of U
b_hat = U @ U.T @ b

# Step 4: Calculate the component in the null space of A^T (z)
z = b - b_hat

# Step 5: Verify if b_hat is in the column space by checking if z is small
print("Projected vector (b_hat):", b_hat)
print("Component in null space (z):", z)
print("Is b_hat in the column space of A?", np.allclose(b_hat, b - z))

Projected vector (b_hat): [[0.08823529]
 [2.85294118]
 [1.38235294]
 [3.97058824]]
Component in null space (z): [[ 0.91176471]
 [-0.85294118]
 [ 1.61764706]
 [ 0.02941176]]
Is b_hat in the column space of A? True


In [18]:
print(S)

[[5.64500387 0.        ]
 [0.         1.46079816]
 [0.         0.        ]
 [0.         0.        ]]


In [19]:
print(V)

NameError: name 'V' is not defined

In [26]:

# Compute the projection of b onto Col(A)
# Col(A) is spanned by the first two columns of U
U_col = U[:, :2]
b_hat = U_col @ U_col.T @ b

# Compute the projection of b onto null(A^T)
# null(A^T) is spanned by the last two columns of U
U_null = U[:, 2:]
z = U_null @ U_null.T @ b

# Display the projections b_hat and z
b_hat, z

(array([[0.08823529],
        [2.85294118],
        [1.38235294],
        [3.97058824]]),
 array([[0.],
        [0.],
        [0.],
        [0.]]))